use_frameworks!

platform :ios, '9.0'

target 'LLCoreData_Example' do
  pod 'LLCoreData', :path => '../'

  target 'LLCoreData_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
